; Generated by AutoGUI 2.5.4
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, ComboBox, x8 y24 w120, Pauses
Gui Add, ListView, x8 y64 w200 h150 +LV0x4000, Macro
Gui Add, Button, x472 y104 w20 h20, 1
Gui Add, Button, x496 y104 w20 h20, 2
Gui Add, Button, x520 y104 w20 h20, 3
Gui Add, Button, x472 y80 w20 h20, 4
Gui Add, Button, x496 y80 w20 h20, 5
Gui Add, Button, x520 y80 w20 h20, 6
Gui Add, Button, x472 y56 w20 h20, 7
Gui Add, Button, x496 y56 w20 h20, 8
Gui Add, Button, x520 y56 w20 h20, 9
Gui Add, Button, x496 y32 w20 h20, /
Gui Add, Button, x520 y32 w20 h20, *
Gui Add, Button, x544 y32 w20 h20, -
Gui Add, Button, x544 y56 w20 h45, +
Gui Add, Button, x544 y104 w20 h45, R
Gui Add, Button, x472 y128 w45 h20, 0
Gui Add, Button, x520 y128 w20 h20, .
Gui Add, GroupBox, x464 y8 w111 h151, Numlock keys
Gui Add, Edit, x200 y16 w120 h21, Name
Gui Add, Button, x233 y95 w80 h23, Record

Gui Show, w620 h420, Window
Return

GuiEscape:
GuiClose:
  ExitApp
